CREATE TABLE IF NOT EXISTS assets (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE assets
ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);

CREATE TABLE IF NOT EXISTS licenses (
  id SERIAL PRIMARY KEY,
  asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  type VARCHAR(100) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  usage VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS license_policies (
  id SERIAL PRIMARY KEY,
  license_id INTEGER NOT NULL UNIQUE REFERENCES licenses(id) ON DELETE CASCADE,
  commercial_use BOOLEAN NOT NULL DEFAULT false,
  ai_training VARCHAR(50) NOT NULL DEFAULT 'not_allowed',
  derivative_works VARCHAR(50) NOT NULL DEFAULT 'not_allowed',
  attribution VARCHAR(50) NOT NULL DEFAULT 'not_required',
  license_scope VARCHAR(50) NOT NULL DEFAULT 'non_exclusive',
  redistribution VARCHAR(50) NOT NULL DEFAULT 'not_allowed',
  usage_type VARCHAR(50) NOT NULL DEFAULT 'commercial',
  policy_version VARCHAR(20) NOT NULL DEFAULT 'v1',
  summary TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchases (
  id SERIAL PRIMARY KEY,
  license_id INTEGER NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,
  buyer_email VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'completed',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
